### PR TITLE
Run CI on GitHub Actions

### LINKED ISSUE #413: The truffleruby-head build should move to allowed failures
Currently it's failing some tests while all other builds pass.

### PR DESCRIPTION
**Pull request by dentarg**
Travis CI is going away for open-source: https://news.ycombinator.com/item?id=25338983

Still one job left on Travis for now for reporting coverage to Coveralls. I'm not sure how that works.

Close #413

### CODE REVIEW

**Comment by dentarg** [comment]
There's one TODO left here, the coverage job actually fails on both Actions and [Travis](https://travis-ci.org/github/sporkmonger/addressable/builds/758978457#L325)

```
Coveralls encountered an exception:
NoMethodError
undefined method `coverage' for #<SimpleCov::SourceFile:0x00000000040d09e0>
Did you mean?  coverage_data
/home/travis/build/sporkmonger/addressable/vendor/bundle/ruby/2.7.0/gems/coveralls-0.7.2/lib/coveralls/simplecov.rb:50:in `block in format'
/home/travis/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/forwardable.rb:235:in `each'
/home/travis/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/forwardable.rb:235:in `each'
/home/travis/build/sporkmonger/addressable/vendor/bundle/ruby/2.7.0/gems/coveralls-0.7.2/lib/coveralls/simplecov.rb:40:in `format'
/home/travis/build/sporkmonger/addressable/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov/result.rb:51:in `format!'
/home/travis/build/sporkmonger/addressable/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov/configuration.rb:197:in `block in at_exit'
/home/travis/build/sporkmonger/addressable/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov.rb:189:in `run_exit_tasks!'
/home/travis/build/sporkmonger/addressable/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov.rb:179:in `at_exit_behavior'
/home/travis/build/sporkmonger/addressable/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov/defaults.rb:30:in `block in <top (required)>'
```

File: spec/spec_helper.rb [hunk 1]
```diff
@@ -16,6 +16,15 @@
     add_filter "spec/"
     add_filter "vendor/"
   end
+end if $LOAD_PATH.join.include?("simplecov")
```
Comment (walro) [inline spec/spec_helper.rb:19]: Perhaps something like this could work too:

```suggestion
end if Gem.loaded_specs.key?("simplecov")
```

Slight modification of https://stackoverflow.com/a/27532804

Comment (dentarg) [reply spec/spec_helper.rb]: Nice, thank you!

**Comment by sporkmonger** [comment]
Thanks for tackling this! I noticed there were some build issues (#413) but given the status of Travis, definitely agree that migrating to GitHub Actions should be the way to address this.

**Comment by sporkmonger** [comment]
What's the rationale for not just deleting `.travis.yml` outright?

**Comment by sporkmonger** [comment]
Oh, that's what you meant on coverage, OK. I think there might be an API key for Coveralls I'll have to figure out.

**Review by sporkmonger — APPROVED** [review]

**Comment by dentarg** [comment]
> There's one TODO left here, the coverage job actually fails on both Actions and [Travis](https://travis-ci.org/github/sporkmonger/addressable/builds/758978457#L325)

I think the issue is that coveralls 0.7.2 is being installed. When it worked on Travis, coveralls 0.8.23 [was installed](https://travis-ci.org/github/sporkmonger/addressable/jobs/758676563#L286).

**Comment by dentarg** [comment]
> I think the issue is that coveralls 0.7.2 is being installed. When it worked on Travis, coveralls 0.8.23 [was installed](https://travis-ci.org/github/sporkmonger/addressable/jobs/758676563#L286).

I tried to understand this more, by trying to replicate the successful Travis build. I checked out the main branch (f839fb28344567c792e148d7a74c529748455d11), and started a Ruby 2.3 docker container (`ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux]`). I ran `bundle install` and bundler installed `coveralls 0.8.23`, but it also failed to install the `idn` gem (because I had forgotten to run `apt-get update && apt-get install -y libidn11-dev`) so the whole `bundle install` failed. I ran the apt commands and ran `bundle install` again. Then Bundler installed `coveralls 0.7.2` 🤯  The output is at https://gist.github.com/dentarg/7c399052b2f589b564f88e8fc76782a4

cc @deivid-rodriguez – I know you don't want to debug Bundler v1.17.3 stuff, which was used above, but I found it quite fascinating. Plus Ruby 2.7.2 and Bundler 2.2.9 also installed coveralls 0.7.2 here on GitHub Actions: https://github.com/sporkmonger/addressable/runs/1899865533?check_suite_focus=true#step:4:65

Oh well, `gem "coveralls", "> 0.7"` seems to do the job here.

**Comment by dentarg** [comment]
> **continuous-integration/travis-ci ** Expected — Waiting for status to be reported

Hmm... not sure this will happen, looks like addressable was migrated from travis-ci.org to travis-ci.com between yesterday and today. https://travis-ci.org/github/sporkmonger/addressable says "This repository was migrated and is now building on travis-ci.com". (The job for 7599df8 links to [.org](https://travis-ci.org/github/sporkmonger/addressable/builds/759684446) while the latest job for e5b3fa2 links to [.com](https://travis-ci.com/github/sporkmonger/addressable/builds/217706982) (via [GitHub](https://github.com/sporkmonger/addressable/runs/1941061297)).

**Comment by dentarg** [comment]
Coveralls does run on GitHub Actions now: https://github.com/sporkmonger/addressable/pull/410/checks?check_run_id=1941061496#step:5:36

```
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Couldn't find a repository matching this job.
Coverage is at 99.28%.
Coverage report sent to Coveralls.
```

> I think there might be an API key for Coveralls I'll have to figure out.

@sporkmonger you need to add that key as a GitHub repository secret here, docs at https://docs.github.com/en/actions/reference/encrypted-secrets

**Comment by dentarg** [comment]
If you do that I can `rm` the Travis config :)

**Comment by dentarg** [comment]
Note to self:

- [ ] configure [`COVERALLS_REPO_TOKEN`](https://github.com/lemurheavy/coveralls-ruby/search?q=COVERALLS_REPO_TOKEN) as `env` on the coverage job, set to the secret added to this repo

**Comment by dentarg** [comment]
Looks like I got Coveralls working? https://coveralls.io/jobs/76665029

**Comment by sporkmonger** [comment]
I dropped Travis as a required check for merge, we can add GH Actions in as a requirement after we merge this.
