### PR TITLE
Check Encodings before calling force_encoding in Addressable::URI

### LINKED ISSUE #254: Constants in Addressable::URI sometimes get mutated
This is an issue I ran into when upgrading to 2.5, but I think other versions are affected in similar ways. Sometimes, when parsing a URL, some of the components of the parsed URL will be set directly to one of the constants defined in `Addressable::URI`. For example, if the path is "/", the instance variable will be set to `Addressable::URI::SLASH`.

If the parsed URL is then normalized, the encoding of `@normalized_path` is forced to be `Encoding::UTF_8`. This mutates the constant. This snippet demonstrates the behavior:

```
[1] pry(main)> Addressable::URI.parse("http://google.com").normalize
=> #<Addressable::URI:0x3fd9d0f0fe44 URI:http://google.com/>
[2] pry(main)> Addressable::URI::SLASH.freeze
=> "/"
[3] pry(main)> Addressable::URI.parse("http://google.com").normalize
RuntimeError: can't modify frozen String
```

The changed behavior is from this commit: https://github.com/sporkmonger/addressable/commit/8f4fee07243af0b788c625e59a9ca529489336d6

This is currently blocking my team from upgrading to 2.5, because we've found value in using the `IceNine` gem to `deep_freeze!` our parsed URLs from Addressable: on more than one occasion it has caught other dependencies of ours mutating URLs in unexpected ways. I understand that this is a non-standard usage of your gem, and understand if as a result, you do not consider this to be a bug.

In the meantime, we will most likely continue using 2.4, but it might be worth thinking about possible solutions here, if only because mutating constants is unexpected.

I think a possible fix would be to either check if the components are already UTF-8 encoded before calling `force_encoding` on them, or to move the `force_encoding` call into the `||= begin` block at the start of each of the `normalized_*` methods.

### PR DESCRIPTION
**Pull request by ACBullen**
Reopening [this pr](https://github.com/sporkmonger/addressable/pull/340) with just the minimum changes to fix the issue blocking our use of the current version.

This is a quick fix to [this issue](https://github.com/sporkmonger/addressable/issues/254), just adding in an extra check to avoid mutating strings when it isn't necessary

Close #254

### CODE REVIEW

**Comment by dentarg** [comment]
> Reopening [this pr](https://github.com/sporkmonger/addressable/pull/340) with just the minimum changes to fix the issue blocking our use of the current version.

I'm curious, what are the issue you are facing with the current version?

> This is a quick fix to [this issue](https://github.com/sporkmonger/addressable/issues/254), just adding in an extra check to avoid mutating strings when it isn't necessary

https://github.com/sporkmonger/addressable/issues/254 is about constants, but this PR only touches instance variables, so I don't think it is the same.

**Comment by ACBullen** [comment]
The issue with constants is sort of an extension of the issue we have right now since we are normalizing the `Addressable::URI` object and then deep freezing. Even if the path or other part of the uri doesn't map to a constant, we are marking all of those strings as intended to be immutable. Since the `force_encoding` runs every time we try to reference parts of the parsed and normalized URI, this causes the same `RuntimeError: can't modify frozen String` to return. 

Without this check, after the strings go through normalization, they are in their final state and do not mutate unless something tries to reassign one of the.

**Comment by dentarg** [comment]
Got it, thanks.

I think we need to add tests for this.

**Comment by baseballlover723** [comment]
@dentarg I have rebased and updated this PR. Let me know if theres anything else you want me to change.

File: spec/addressable/uri_spec.rb [hunk 1]
```diff
@@ -999,6 +999,72 @@ def to_s
...
+  it "#normalized_fragment should not error" do
+    expect { @uri.normalized_fragment }.not_to raise_error
+  end
+
+  it "should be frozen" do
+    expect(@uri).to be_frozen
+  end
+
+  it "should not allow destructive operations" do
+    expect { @uri.normalize! }.to raise_error(FrozenError)
```
Comment (dentarg) [inline spec/addressable/uri_spec.rb:1064]: `FrozenError` only exist [in Ruby 2.5 and newer](https://docs.ruby-lang.org/en/2.5.0/NEWS.html) (I just learned this too). Sounds like it was `RuntimeError` before: https://github.com/jruby/jruby/pull/5106

Hence the test failures. Do you mind addressing this?

Comment (baseballlover723) [reply spec/addressable/uri_spec.rb]: I just pushed some changes

**Comment by baseballlover723** [comment]
@dentarg This is ready for review again

File: spec/addressable/uri_spec.rb [hunk 2]
```diff
@@ -998,6 +998,74 @@ def to_s
...
+    expect { @uri.normalized_fragment }.not_to raise_error
+  end
+
+  it "should be frozen" do
+    expect(@uri).to be_frozen
+  end
+
+  it "should not allow destructive operations" do
+    ruby_check = Gem::Version.new(RUBY_VERSION) < Gem::Version.new("2.5.0")
+    error = ruby_check ? RuntimeError : FrozenError
```
Comment (sporkmonger) [inline spec/addressable/uri_spec.rb:1064]: I'd prefer to have this test not care at all which error is raised.

**Review by sporkmonger — CHANGES_REQUESTED** [review]

File: spec/addressable/uri_spec.rb (hunk 2 above)
Comment (dentarg) [reply spec/addressable/uri_spec.rb:1064]: Not sure I'm following... it says `should not allow destructive operations` and we expect `@uri.normalize!` to raise RuntimeError/FrozenError (`can't modify frozen String`). Is that because you shouldn't be able to use `#normalize!` on a frozen `Addressable::URI`? Maybe we can make that even more clear in the test? (The `@uri.freeze` happens way up in the `before` block so it is easy to miss)

Maybe `Addressable::URI#normalize!` should detect that the URI is frozen and raise an error defined by Addressable? (`FrozenURIError` perhaps?)

---

Ah, this particular spec doesn't test the changes made in this branch, I ran this against Addressable 2.8.0

```ruby
# Ruby 2.4.3

irb(main):005:0* @uri = Addressable::URI.parse("http://user:password@example.com:8080/path?query=value#fragment")
=> #<Addressable::URI:0x3ff6e204dd78 URI:http://user:password@example.com:8080/path?query=value#fragment>
irb(main):006:0> @uri.freeze
=> #<Addressable::URI:0x3ff6e204dd78 URI:http://user:password@example.com:8080/path?query=value#fragment>
irb(main):007:0> @uri.normalize!
RuntimeError: can't modify frozen Addressable::URI
	from /Users/dentarg/.gem/ruby/2.4.3/gems/addressable-2.8.0/lib/addressable/uri.rb:2518:in `remove_instance_variable'
	from /Users/dentarg/.gem/ruby/2.4.3/gems/addressable-2.8.0/lib/addressable/uri.rb:2518:in `block in replace_self'
	from /Users/dentarg/.gem/ruby/2.4.3/gems/addressable-2.8.0/lib/addressable/uri.rb:2516:in `each'
	from /Users/dentarg/.gem/ruby/2.4.3/gems/addressable-2.8.0/lib/addressable/uri.rb:2516:in `replace_self'
	from /Users/dentarg/.gem/ruby/2.4.3/gems/addressable-2.8.0/lib/addressable/uri.rb:2211:in `normalize!'
	from (irb):7
	from /Users/dentarg/.rubies/2.4.3/bin/irb:11:in `<main>'
```

```ruby
# Ruby 3.1.2

irb(main):005:0> @uri = Addressable::URI.parse("http://user:password@example.com:8080/path?query=value#fragment")
=> #<Addressable::URI:0xb43c URI:http://user:password@example.com:8080/path?query=value#fragment>
irb(main):006:0>
irb(main):007:0> @uri.freeze
=> #<Addressable::URI:0xb43c URI:http://user:password@example.com:8080/path?query=value#fragment>
irb(main):008:0> @uri.normalize!
/Users/dentarg/.gem/ruby/3.1.2/gems/addressable-2.8.0/lib/addressable/uri.rb:2518:in `remove_instance_variable': can't modify frozen Addressable::URI: #<Addressable::URI:0xb43c URI:http://user:password@example.com:8080/path?query=value#fragment> (FrozenError)
	from /Users/dentarg/.gem/ruby/3.1.2/gems/addressable-2.8.0/lib/addressable/uri.rb:2518:in `block in replace_self'
	from /Users/dentarg/.gem/ruby/3.1.2/gems/addressable-2.8.0/lib/addressable/uri.rb:2516:in `each'
	from /Users/dentarg/.gem/ruby/3.1.2/gems/addressable-2.8.0/lib/addressable/uri.rb:2516:in `replace_self'
	from /Users/dentarg/.gem/ruby/3.1.2/gems/addressable-2.8.0/lib/addressable/uri.rb:2211:in `normalize!'
	from (irb):8:in `<main>'
	from /Users/dentarg/.rubies/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /Users/dentarg/.rubies/3.1.2/bin/irb:25:in `load'
	from /Users/dentarg/.rubies/3.1.2/bin/irb:25:in `<main>'
```

Perhaps we shouldn't change this behaviour as I suggested above

---

@sporkmonger should we just check error message? Expect `can't modify frozen Addressable::URI`. Those can change from Ruby to Ruby version too, but probably unlikely in this case IMHO.

Comment (sporkmonger) [reply spec/addressable/uri_spec.rb:1064]: Mostly I'd prefer to have the test make the same checks regardless of Ruby version. If the error message is consistent between versions but the type is not, it seems fine to check the error message, but if that's inconsistent too, I think it's fine to verify that an error, any error, has been thrown.

Comment (dentarg) [reply spec/addressable/uri_spec.rb]: We can have the test make the same checks regardless of Ruby version. If we look at the hierarchy of exceptions at https://ruby-doc.org/core-2.6.5/Exception.html we can see that FrozenError is a subclass of RuntimeError. That should never change really. We can use `#is_a?` and always check if it is a RuntimeError:

```ruby
irb(main):007:1* ex = begin
irb(main):008:1*   raise FrozenError, "can't modify frozen String"
irb(main):009:1* rescue => e
irb(main):010:1*   e
irb(main):011:0> end
=> #<FrozenError: can't modify frozen String>
irb(main):012:0> ex.inspect
=> "#<FrozenError: can't modify frozen String>"
irb(main):013:0> ex.is_a?(RuntimeError)
=> true
```

File: spec/addressable/uri_spec.rb [hunk 3]
```diff
@@ -998,6 +998,75 @@ def to_s
...
+  end
+
+  it "should be frozen" do
+    expect(@uri).to be_frozen
+  end
+
+  it "should not allow destructive operations" do
+    expect { @uri.normalize! }.to raise_error { |error|
+      expect(error.message).to match(/can't modify frozen/)
+      expect(error).to satisfy { |e| RuntimeError === e || TypeError === e }
```
[the remark this answers is not in the document]
Comment (dentarg) [reply spec/addressable/uri_spec.rb:1065]: See https://github.com/sporkmonger/addressable/pull/341#discussion_r934145690

File: spec/addressable/uri_spec.rb (hunk 2 above)
Comment (dentarg) [reply spec/addressable/uri_spec.rb]: (We don't need to check the message)

Comment (baseballlover723) [reply spec/addressable/uri_spec.rb]: Are there any other changes required? I've implemented the above changes.

Comment (dentarg) [reply spec/addressable/uri_spec.rb]: Looks good now, thanks!

**Review by dentarg — APPROVED** [review]
